matrix:
  allow_failures:
    - env: GHCVER=head

env:
 - GHCVER=7.8.2
 - GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.20 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.20 update
 - travis_retry cabal-1.20 install -j2 alex happy

script:
 - travis_retry cabal-1.20 install -j2 --enable-tests --only-dependencies
 - cabal-1.20 install --enable-tests
