matrix:
  allow_failures:
    - env: GHCVER=head

env:
 - GHCVER=7.8.1
 - GHCVER=head
 - HPVER=2013.2.0.0
 - HPVER=2012.4.0.0

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.18 update
 - travis_retry cabal-1.18 install -j2 alex happy

script:
 - travis_retry cabal-1.18 install -j2 --enable-tests --only-dependencies
 - cabal-1.18 install --enable-tests
