resolver: lts-3.9
packages:
- '.'
- location:
    git: https://github.com/meteogrid/spatial-reference.git
    commit: 19e686dfab907443019216b96c1584fbe938fa29
  extra-dep: true

extra-deps:
  - linear-1.20.2
  - vector-0.11.0.0
  - vector-th-unbox-0.2.1.3
