resolver: lts-5.11
packages:
- '.'
- location:
    git: https://github.com/meteogrid/spatial-reference.git
    commit: de83fe1319e14937c71e82baeca3f5f3411d1a49
  extra-dep: true
extra-deps:
  - vector-0.11.0.0
  - vector-th-unbox-0.2.1.3
